---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: icinga-monitor-pods
subjects:
- kind: ServiceAccount
  name: icinga-monitoring-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: icinga-monitoring
  apiGroup: rbac.authorization.k8s.io
